/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Github, 
  Linkedin, 
  Mail, 
  ExternalLink, 
  Code2, 
  Cpu, 
  Database, 
  Layout, 
  Terminal, 
  ChevronRight,
  Menu,
  X,
  FileText,
  Users
} from 'lucide-react';
import { cn } from './lib/utils';

const PROJECTS = [
  {
    title: "AI Document Q&A System",
    description: "Built an end-to-end RAG pipeline allowing users to upload PDFs and ask natural-language questions. Answers are generated by Llama 3.2 locally using FAISS vector store.",
    tech: ["Python", "LangChain", "FAISS", "Ollama", "Streamlit"],
    type: "Personal",
    link: "https://github.com/sreekanthbathala",
    icon: <Cpu className="w-6 h-6" />
  },
  {
    title: "College Management System",
    description: "A full-stack MERN application with RESTful APIs to manage student and course records. Features a responsive React frontend and clean UI design.",
    tech: ["React", "Node.js", "Express", "MongoDB"],
    type: "Personal",
    link: "https://github.com/sreekanthbathala",
    icon: <Layout className="w-6 h-6" />
  },
  {
    title: "Multi-Agent Research Assistant",
    description: "Collaborative team project developing a swarm of AI agents that perform deep research on technical topics and generate comprehensive reports.",
    tech: ["Python", "LangChain", "OpenAI API", "React"],
    type: "Team",
    link: "#",
    icon: <Users className="w-6 h-6" />
  },
  {
    title: "Distributed Vector Database",
    description: "Team project focused on scaling vector search for millions of embeddings using a distributed architecture and optimized indexing.",
    tech: ["Go", "gRPC", "ChromaDB", "Docker"],
    type: "Team",
    link: "#",
    icon: <Database className="w-6 h-6" />
  }
];

const SKILLS = [
  { category: "AI / ML", items: ["Generative AI", "LLMs", "RAG", "Prompt Engineering", "FAISS", "ChromaDB", "Hugging Face"] },
  { category: "Frameworks", items: ["LangChain", "Ollama", "Streamlit", "React.js", "Node.js", "Express.js"] },
  { category: "Languages", items: ["Python", "JavaScript", "C"] },
  { category: "Databases", items: ["MongoDB", "FAISS", "ChromaDB"] },
  { category: "Tools", items: ["Git", "GitHub", "VS Code", "Netlify", "Render"] }
];

const EDUCATION = [
  {
    degree: "B.Tech – Computer Science & Engineering",
    institution: "Madanapalle Institute of Technology & Science (MITS)",
    period: "2024 – 2028",
    status: "Current"
  },
  {
    degree: "Board of Intermediate Education (Class XI – XII)",
    institution: "Narayana Junior College, Andhra Pradesh",
    period: "2022 – 2024",
    status: "Completed"
  }
];



export default function App() {
  const [activeTab, setActiveTab] = useState('All');
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const filteredProjects = activeTab === 'All' 
    ? PROJECTS 
    : PROJECTS.filter(p => p.type === activeTab);

  return (
    <div className="min-h-screen bg-brand-bg text-brand-ink selection:bg-brand-accent selection:text-brand-bg">
      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 border-bottom border-brand-border bg-brand-bg/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-brand-accent rounded-sm flex items-center justify-center">
              <span className="text-brand-bg font-bold font-mono">SB</span>
            </div>
            <span className="font-mono text-sm tracking-tighter uppercase hidden sm:block">Sreekanth Bathala</span>
          </div>

          <div className="hidden md:flex items-center gap-8">
            {['About', 'Skills', 'Projects', 'Education', 'Contact'].map((item) => (
              <a 
                key={item} 
                href={`#${item.toLowerCase()}`}
                className="text-xs uppercase tracking-widest text-brand-muted hover:text-brand-accent transition-colors"
              >
                {item}
              </a>
            ))}
          </div>

          <button 
            className="md:hidden text-brand-ink"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            {isMenuOpen ? <X /> : <Menu />}
          </button>
        </div>
      </nav>

      {/* Mobile Menu */}
      <AnimatePresence>
        {isMenuOpen && (
          <motion.div 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed inset-0 z-40 bg-brand-bg pt-24 px-6 md:hidden"
          >
            <div className="flex flex-col gap-8">
              {['About', 'Skills', 'Projects', 'Education', 'Contact'].map((item) => (
                <a 
                  key={item} 
                  href={`#${item.toLowerCase()}`}
                  onClick={() => setIsMenuOpen(false)}
                  className="text-2xl font-bold uppercase tracking-tighter"
                >
                  {item}
                </a>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <main className="pt-20">
        {/* Hero Section */}
        <section id="about" className="max-w-7xl mx-auto px-6 py-24 md:py-40 border-bottom border-brand-border">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 px-3 py-1 border border-brand-accent/30 rounded-full mb-6">
                <span className="w-2 h-2 bg-brand-accent rounded-full animate-pulse" />
                <span className="text-[10px] uppercase tracking-widest text-brand-accent font-medium">Available for Internships</span>
              </div>
              <h1 className="text-6xl md:text-8xl font-bold tracking-tighter leading-[0.9] mb-8 uppercase">
                AI/ML <br />
                <span className="text-brand-accent">Engineer</span>
              </h1>
              <p className="text-lg text-brand-muted max-w-xl mb-10 leading-relaxed">
                B.Tech CSE student at MITS with hands-on experience in Python, Generative AI, and Retrieval-Augmented Generation (RAG). Building intelligent systems that bridge the gap between human intent and machine execution.
              </p>
              <div className="flex flex-wrap gap-4">
                <a 
                  href="#projects" 
                  className="px-8 py-4 bg-brand-accent text-brand-bg font-bold uppercase text-xs tracking-widest hover:bg-white transition-colors"
                >
                  View Projects
                </a>
                <a 
                  href="mailto:sreekanthbathala8@gmail.com" 
                  className="px-8 py-4 border border-brand-border font-bold uppercase text-xs tracking-widest hover:border-brand-accent transition-colors"
                >
                  Get in Touch
                </a>
              </div>
            </motion.div>

            <motion.div 
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="relative hidden lg:block"
            >
              <div className="aspect-square border border-brand-border rounded-2xl p-8 flex items-center justify-center overflow-hidden">
                <div className="absolute inset-0 bg-radial-gradient from-brand-accent/10 to-transparent opacity-50" />
                <Terminal className="w-48 h-48 text-brand-accent/20" />
                <div className="absolute bottom-12 left-12 right-12 bg-brand-bg/80 backdrop-blur-md border border-brand-border p-6 rounded-xl">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="flex gap-1">
                      <div className="w-2 h-2 rounded-full bg-red-500/50" />
                      <div className="w-2 h-2 rounded-full bg-yellow-500/50" />
                      <div className="w-2 h-2 rounded-full bg-green-500/50" />
                    </div>
                    <span className="text-[10px] font-mono text-brand-muted">sreekanth@mits:~/portfolio</span>
                  </div>
                  <div className="font-mono text-xs space-y-2">
                    <p className="text-brand-accent">$ whoami</p>
                    <p className="text-brand-ink">Sreekanth Bathala</p>
                    <p className="text-brand-accent">$ skills --list</p>
                    <p className="text-brand-ink">Python, JS, RAG, LLMs, MERN</p>
                    <p className="text-brand-accent">$ status</p>
                    <p className="text-brand-ink animate-pulse">Building the future...</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Skills Section */}
        <section id="skills" className="max-w-7xl mx-auto px-6 py-24 border-bottom border-brand-border">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-8">
            <div>
              <span className="text-xs uppercase tracking-[0.3em] text-brand-accent font-bold mb-4 block">01 / Expertise</span>
              <h2 className="text-4xl md:text-6xl font-bold tracking-tighter uppercase">Technical Stack</h2>
            </div>
            <p className="text-brand-muted max-w-md">
              Specialized in modern AI architectures and full-stack web development, focusing on performance and scalability.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-brand-border border border-brand-border">
            {SKILLS.map((skill, idx) => (
              <div key={idx} className="bg-brand-bg p-10 hover:bg-brand-accent/5 transition-colors group">
                <h3 className="text-xs font-mono text-brand-muted uppercase tracking-widest mb-6 group-hover:text-brand-accent transition-colors">
                  {skill.category}
                </h3>
                <div className="flex flex-wrap gap-2">
                  {skill.items.map((item, i) => (
                    <span key={i} className="px-3 py-1 bg-brand-border/50 text-[11px] font-medium uppercase tracking-wider">
                      {item}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Projects Section */}
        <section id="projects" className="max-w-7xl mx-auto px-6 py-24 border-bottom border-brand-border">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-8">
            <div>
              <span className="text-xs uppercase tracking-[0.3em] text-brand-accent font-bold mb-4 block">02 / Portfolio</span>
              <h2 className="text-4xl md:text-6xl font-bold tracking-tighter uppercase">Selected Works</h2>
            </div>
            
            <div className="flex gap-2">
              {['All', 'Personal', 'Team'].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={cn(
                    "px-6 py-2 text-[10px] uppercase tracking-widest font-bold transition-all",
                    activeTab === tab 
                      ? "bg-brand-accent text-brand-bg" 
                      : "border border-brand-border text-brand-muted hover:border-brand-accent"
                  )}
                >
                  {tab}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {filteredProjects.map((project, idx) => (
              <motion.div 
                layout
                key={project.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                whileHover={{ 
                  scale: 1.02,
                  boxShadow: "0 20px 40px -15px rgba(0, 255, 0, 0.15)",
                }}
                transition={{ 
                  duration: 0.4,
                  scale: { type: "spring", stiffness: 300, damping: 20 }
                }}
                className="group border border-brand-border p-8 hover:border-brand-accent transition-colors flex flex-col h-full bg-brand-bg relative z-0 overflow-hidden"
              >
                <div className="flex items-start justify-between mb-8">
                  <motion.div 
                    whileHover={{ rotate: 12, scale: 1.1 }}
                    className="p-3 bg-brand-border/30 text-brand-accent"
                  >
                    {project.icon}
                  </motion.div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] uppercase tracking-widest font-bold text-brand-muted">
                      {project.type}
                    </span>
                    <a href={project.link} className="text-brand-muted hover:text-brand-accent transition-colors">
                      <ExternalLink className="w-4 h-4" />
                    </a>
                  </div>
                </div>
                
                <h3 className="text-2xl font-bold uppercase tracking-tight mb-4 group-hover:text-brand-accent transition-colors">
                  {project.title}
                </h3>
                <p className="text-brand-muted text-sm leading-relaxed mb-8 flex-grow">
                  {project.description}
                </p>
                
                <div className="flex flex-wrap gap-2 pt-6 border-t border-brand-border">
                  {project.tech.map((t, i) => (
                    <motion.span 
                      key={i} 
                      variants={{
                        hover: { y: -4, color: "var(--color-brand-accent)" }
                      }}
                      transition={{ delay: i * 0.05 }}
                      className="text-[9px] font-mono uppercase tracking-widest text-brand-muted group-hover:text-brand-accent transition-colors"
                    >
                      {t}
                    </motion.span>
                  ))}
                </div>

                {/* Subtle glow effect on hover */}
                <motion.div 
                  initial={{ opacity: 0 }}
                  whileHover={{ opacity: 1 }}
                  className="absolute inset-0 bg-radial-gradient from-brand-accent/5 to-transparent -z-10 pointer-events-none"
                />
              </motion.div>
            ))}
          </div>
        </section>

        {/* Education Section */}
        <section id="education" className="max-w-7xl mx-auto px-6 py-24 border-bottom border-brand-border">
          <div className="mb-16">
            <span className="text-xs uppercase tracking-[0.3em] text-brand-accent font-bold mb-4 block">03 / Background</span>
            <h2 className="text-4xl md:text-6xl font-bold tracking-tighter uppercase">Education</h2>
          </div>

          <div className="space-y-12">
            {EDUCATION.map((edu, idx) => (
              <div key={idx} className="grid grid-cols-1 md:grid-cols-4 gap-8 items-start">
                <div className="md:col-span-1">
                  <span className="text-xs font-mono text-brand-muted uppercase tracking-widest">
                    {edu.period}
                  </span>
                </div>
                <div className="md:col-span-3">
                  <div className="flex items-center gap-3 mb-2">
                    <h3 className="text-xl font-bold uppercase tracking-tight">{edu.degree}</h3>
                    <span className={cn(
                      "px-2 py-0.5 text-[9px] uppercase tracking-widest font-bold rounded-sm",
                      edu.status === 'Current' ? "bg-brand-accent text-brand-bg" : "bg-brand-border text-brand-muted"
                    )}>
                      {edu.status}
                    </span>
                  </div>
                  <p className="text-brand-muted uppercase text-xs tracking-widest font-medium">
                    {edu.institution}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" className="max-w-7xl mx-auto px-6 py-24 md:py-40">
          <div className="text-center max-w-3xl mx-auto">
            <span className="text-xs uppercase tracking-[0.3em] text-brand-accent font-bold mb-8 block">04 / Connect</span>
            <h2 className="text-5xl md:text-7xl font-bold tracking-tighter uppercase mb-12">
              Let's build <br />
              <span className="text-brand-accent">Something Great</span>
            </h2>
            
            <div className="flex flex-wrap justify-center gap-8 mb-16">
              <a 
                href="https://github.com/sreekanthbathala" 
                target="_blank" 
                rel="noreferrer"
                className="flex items-center gap-3 text-brand-muted hover:text-brand-accent transition-colors group"
              >
                <Github className="w-6 h-6" />
                <span className="text-xs uppercase tracking-widest font-bold">GitHub</span>
              </a>
              <a 
                href="https://linkedin.com/in/sreekanth-bathala" 
                target="_blank" 
                rel="noreferrer"
                className="flex items-center gap-3 text-brand-muted hover:text-brand-accent transition-colors group"
              >
                <Linkedin className="w-6 h-6" />
                <span className="text-xs uppercase tracking-widest font-bold">LinkedIn</span>
              </a>
              <a 
                href="mailto:sreekanthbathala8@gmail.com" 
                className="flex items-center gap-3 text-brand-muted hover:text-brand-accent transition-colors group"
              >
                <Mail className="w-6 h-6" />
                <span className="text-xs uppercase tracking-widest font-bold">Email</span>
              </a>
              <p><a href="tel:+918309489027">+91 8309489027</a></p>
            </div>
          </div>
        </section>
      </main>

      <footer className="max-w-7xl mx-auto px-6 py-12 border-t border-brand-border flex flex-col md:flex-row justify-between items-center gap-6">
        <p className="text-[10px] uppercase tracking-widest text-brand-muted">
          © 2024 Sreekanth Bathala. All Rights Reserved.
        </p>
      </footer>
    </div>
  );
}
